package uk.ac.stfc.facilities.client.rest.resources;

import jakarta.json.Json;
import jakarta.json.JsonObject;

import static uk.ac.stfc.facilities.client.rest.base.Constants.*;

public class RorPayloadBuilder {
    public static String buildTestRorPayload() {
        JsonObject body = Json.createObjectBuilder()
                .add("admin", Json.createObjectBuilder()
                        .add("created", Json.createObjectBuilder()
                                .add("date", "2018-11-14")
                                .add("schema_version", "1.0"))
                        .add("last_modified", Json.createObjectBuilder()
                                .add("date", "2025-05-05")
                                .add("schema_version", "2.1")))
                .add("domains", Json.createArrayBuilder()) // empty []
                .add("established", 1829)
                .add("external_ids", Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("all", Json.createArrayBuilder()
                                        .add("100009360")
                                        .add("501100004074")
                                        .add("501100000656")
                                        .add("501100000764")
                                        .add("100011885")
                                        .add("100013376")
                                        .add("100014542"))
                                .add("type", "fundref")
                                .add("preferred", "100009360"))
                        .add(Json.createObjectBuilder()
                                .add("all", Json.createArrayBuilder().add("grid.13097.3c"))
                                .add("type", "grid")
                                .add("preferred", "grid.13097.3c"))
                        .add(Json.createObjectBuilder()
                                .add("all", Json.createArrayBuilder().add("0000 0001 2322 6764"))
                                .add("type", "isni"))
                        .add(Json.createObjectBuilder()
                                .add("all", Json.createArrayBuilder().add("Q245247"))
                                .add("type", "wikidata")))
                .add("id", ROR_PAYLOAD_ROR_ID)
                .add("links", Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("value", ROR_PAYLOAD_URL)
                                .add("type", "website"))
                        .add(Json.createObjectBuilder()
                                .add("value", "http://en.wikipedia.org/wiki/King's_College_London")
                                .add("type", "wikipedia")))
                .add("locations", Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("geonames_id", 2643743)
                                .add("geonames_details", Json.createObjectBuilder()
                                        .add("name", "London")
                                        .add("lat", 51.50853)
                                        .add("lng", -0.12574)
                                        .add("continent_code", "EU")
                                        .add("continent_name", "Europe")
                                        .add("country_code", "GB")
                                        .add("country_name", ROR_PAYLOAD_COUNTRY)
                                        .add("country_subdivision_code", "ENG")
                                        .add("country_subdivision_name", "England"))))
                .add("names", Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("value", ROR_PAYLOAD_LABEL)
                                .add("types", Json.createArrayBuilder().add("label"))
                                .add("lang", "cy"))
                        .add(Json.createObjectBuilder()
                                .add("value", ROR_PAYLOAD_ACRONYM)
                                .add("types", Json.createArrayBuilder().add("acronym")))
                        .add(Json.createObjectBuilder()
                                .add("value", ROR_PAYLOAD_ALIAS)
                                .add("types", Json.createArrayBuilder().add("alias")))
                        .add(Json.createObjectBuilder()
                                .add("value", ROR_PAYLOAD_NAME)
                                .add("types", Json.createArrayBuilder()
                                        .add("ror_display")
                                        .add("label"))
                                .add("lang", "en")))
                .add("relationships", Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("type", "child")
                                .add("id", "https://ror.org/04s9kfd63")
                                .add("label", "Wellcome EPSRC Centre for Medical Engineering")))
                .add("status", "active")
                .add("types", Json.createArrayBuilder()
                        .add(ROR_PAYLOAD_TYPE_1)
                        .add(ROR_PAYLOAD_TYPE_2))
                .build();

        return body.toString();
    }
}
