name: Main Rest Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "40 0 * * *" # 00:40 UTC, daily

permissions:
  packages: read
  contents: read
  pull-requests: read

jobs:
  rest-test:
    permissions:
      packages: read
      contents: read
      id-token: write
    runs-on: fase-self-hosted
    container: ghcr.io/isisbusapps/fase-gh-runner-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          server-id: gitea
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Run Maven Tests
        env:
          MAVEN_USERNAME: ${{ secrets.GITEA_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
          REST_URI: https://devapis.facilities.rl.ac.uk/establishment-service
          SUPER_ADMIN_TOKEN: ${{ secrets.SUPER_ADMIN_TOKEN }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          USER_OFFICE_TOKEN: ${{ secrets.USER_OFFICE_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          GET_ALL_BASICPERSONDETAILS_API_KEY: ${{ secrets.GET_ALL_BASIC_PERSONDETAILS_API_KEY }}
          GET_ALL_PERSONDETAILS_API_KEY: ${{ secrets.GET_ALL_PERSONDETAILS_API_KEY }}
          FAP_API_KEY: ${{ secrets.FAP_API_KEY }}
          ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
          ISISBUSAPPS_CI_FED_ID: ${{ secrets.ISISBUSAPPS_CI_FED_ID }}
          ISISBUSAPPS_CI_PASSWORD: ${{ secrets.ISISBUSAPPS_CI_PASSWORD }}
          DB_USERNAME: ${{ secrets.DEV_USERDBUSERNAME }}
          DB_PASSWORD: ${{ secrets.DEV_USERDBPASSWORD }}
          DB_URL: ${{ secrets.DEV_DATABASEURL }}
        run: mvn -B clean test -D'userOfficeTest.restUri'=$REST_URI -D'db.url'=$DB_URL -D'db.username'=$DB_USERNAME -D'db.password'=$DB_PASSWORD -f establishment-rest-service-test/pom.xml