name: DEV Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || 'dev-deploy' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  dev-build:
    uses: isisbusapps/ci-cd/.github/workflows/dev-build-reusable-workflow.yaml@main
    with:
      image-name: establishment-service
      app-name: Establishment Service
      gitops-patch-path: components/ua/establishment-service/overlays/dev/patch-image.yaml
      use-dockerhub-mirror: true
    secrets:
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
