name: [DEV] Build and deploy

on:
  push:
    branches:
      - develop
    paths-ignore:
      - README.md

concurrency:
  group: dev-deploy
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  APP_NAME: Establishment Service
  IMAGE_NAME: ${{ github.repository }}
  GITOPS_REPO: isisbusapps/gitops
  GITOPS_PATCH_PATH: components/ua/establishment-service/overlays/dev/patch-image.yml
  TAGS: dev

jobs:
  build_and_push:
    name: Build and Push Container
    runs-on: self-hosted
    timeout-minutes: 30

    permissions:
      packages: write
      contents: read

    outputs:
      image-digest: ${{ steps.docker_build.outputs.digest }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update_gitops:
    name: Update GitOps Repository
    runs-on: self-hosted
    timeout-minutes: 10
    needs: build_and_push
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update image reference
        uses: mikefarah/yq@v4.48.1
        with:
          cmd: |
            yq e -i '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build_and_push.outputs.image-digest }}"' \
              './${{ env.GITOPS_PATCH_PATH }}'

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[CD] Update ${{ env.APP_NAME }} with this commit ${{ github.event.head_commit.url}}"
          git push
